### ISSUE TITLE
Documented classes .hide-for-small etc don't exist

### ISSUE THREAD

**Issue by jameshfisher** [pusher/chameleon#40]

**Comment by craigthomasfrost** [comment]
If we're talking about the same thing, these do exist. `.scss` file can be found here:

https://github.com/pusher/chameleon/blob/master/stylesheets/components/_visibility.scss

Styles can be imported into a project explicitly with:

`@include CHAMELEON-visibility-classes;`

**Comment by jameshfisher** [comment]
@craigthomasfrost Ahhhh yes I was being stupid! What a nice response to my silly invalid issue.
